hashcheck for buildandtest admin-dashboard

diff --git a/ci/spec/admin-dashboard/build-n-test.yaml b/ci/spec/admin-dashboard/build-n-test.yaml
--- a/ci/spec/admin-dashboard/build-n-test.yaml
+++ b/ci/spec/admin-dashboard/build-n-test.yaml
@@ -1,43 +1,83 @@
 build_n_test_admin-dashboard:
-  stage: BuildAndTest
-  script:
-    - curl -sSL https://get.docker.com/ | sh #Install docker.
-    - cd admin-dashboard
-    - npm ci
-      # try building, if there are warnings then this will fail
-    - npm run build
-    - echo "No test implemented"
-  except:
-    refs:
-      - hotfix-master
-      - hotfix-release
+    stage: BuildAndTest
+    script:
+        - |
+            if [[ $CI_COMMIT_BRANCH != "master" ]] && [[ $CI_COMMIT_BRANCH != "release" ]]
+            then
+                chmod +x ./ci/scripts/checkhash.sh
+                export admin_dashboard_exist=`./ci/scripts/checkhash.sh build_n_test_admin-dashboard admin-dashboard`
+                if [[ $admin_dashboard_exist == *"true"* ]]
+                then
+                    exit ${CI_JOB_SKIP_EXIT_CODE:-0}
+                fi
+            fi
+        - curl -sSL https://get.docker.com/ | sh #Install docker.
+        - cd admin-dashboard
+        - npm ci
+          # try building, if there are warnings then this will fail
+        - npm run build
+        - echo "No test implemented"
+        - cd ..
+        - |
+            if [[ $CI_COMMIT_BRANCH != "master" ]] && [[ $CI_COMMIT_BRANCH != "release" ]]
+            then
+                chmod +x ./ci/scripts/storehash.sh
+                ./ci/scripts/storehash.sh build_n_test_admin-dashboard admin-dashboard
+            fi
+    except:
+        refs:
+            - hotfix-master
+            - hotfix-release
 
 build_n_test_enterprise_admin-dashboard:
-  stage: BuildAndTest
-  script:
-    - sudo apt-get update
-    - curl -sSL https://get.docker.com/ | sh #Install docker.
-    - sudo apt install -y gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
-    - echo "Setup machine for running puppeteer tests"
-    - sudo docker stop $(sudo docker ps -aq) || echo 'No docker containers'
-    - sudo docker rm $(sudo docker ps -aq) || echo 'No docker containers'
-    - sudo docker run --name mongo -p 27017:27017 -d mongo:4.2.3
-    - sudo docker run --name redis -p 6379:6379 -d redis:5.0.7 redis-server
-    - sudo docker build -t fyipeproject/backend:3.0.$CI_PIPELINE_IID ./backend
-    - sudo docker run --env-file ./backend/.env --net=host -d fyipeproject/backend:3.0.$CI_PIPELINE_IID
-    - sudo docker build -t fyipeproject/licensing:3.0.$CI_PIPELINE_IID ./licensing
-    - sudo docker run --env-file ./licensing/.env -p 3004:3004 -d fyipeproject/licensing:3.0.$CI_PIPELINE_IID
-    - sudo docker build -t fyipeproject/accounts:3.0.$CI_PIPELINE_IID ./accounts
-    - sudo docker run --env-file ./accounts/.env -p 3003:3003 -d fyipeproject/accounts:3.0.$CI_PIPELINE_IID
-    - sudo docker build -t fyipeproject/admin-dashboard:3.0.$CI_PIPELINE_IID ./admin-dashboard
-    - sudo docker run --env-file ./admin-dashboard/.env -p 3100:3100 -d fyipeproject/admin-dashboard:3.0.$CI_PIPELINE_IID    
-    - sudo docker ps
-    - cd admin-dashboard
-    - npm ci
-    # try building, if there are warnings then this will fail
-    - npm run build
-    - npm run enterprise-test
-  except:
-    refs:
-      - hotfix-master
-      - hotfix-release
+    stage: BuildAndTest
+    script:
+        - |
+            if [[ $CI_COMMIT_BRANCH != "master" ]] && [[ $CI_COMMIT_BRANCH != "release" ]]
+            then
+                chmod +x ./ci/scripts/checkhash.sh
+                export backend_exist=`./ci/scripts/checkhash.sh build_n_test_enterprise_admin-dashboard backend`
+                export accounts_exist=`./ci/scripts/checkhash.sh build_n_test_enterprise_admin-dashboard accounts`
+                export licensing_exist=`./ci/scripts/checkhash.sh build_n_test_enterprise_admin-dashboard licensing`
+                export admin_dashboard_exist=`./ci/scripts/checkhash.sh build_n_test_enterprise_admin-dashboard admin-dashboard`
+                if [[ $admin_dashboard_exist == *"true"* ]] && [[ $backend_exist == *"true"* ]] && [[ $accounts_exist == *"true"* ]] && [[ $licensing_exist == *"true"* ]]
+                then
+                    exit ${CI_JOB_SKIP_EXIT_CODE:-0}
+                fi
+            fi
+        - sudo apt-get update
+        - curl -sSL https://get.docker.com/ | sh #Install docker.
+        - sudo apt install -y gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
+        - echo "Setup machine for running puppeteer tests"
+        - sudo docker stop $(sudo docker ps -aq) || echo 'No docker containers'
+        - sudo docker rm $(sudo docker ps -aq) || echo 'No docker containers'
+        - sudo docker run --name mongo -p 27017:27017 -d mongo:4.2.3
+        - sudo docker run --name redis -p 6379:6379 -d redis:5.0.7 redis-server
+        - sudo docker build -t fyipeproject/backend:3.0.$CI_PIPELINE_IID ./backend
+        - sudo docker run --env-file ./backend/.env --net=host -d fyipeproject/backend:3.0.$CI_PIPELINE_IID
+        - sudo docker build -t fyipeproject/licensing:3.0.$CI_PIPELINE_IID ./licensing
+        - sudo docker run --env-file ./licensing/.env -p 3004:3004 -d fyipeproject/licensing:3.0.$CI_PIPELINE_IID
+        - sudo docker build -t fyipeproject/accounts:3.0.$CI_PIPELINE_IID ./accounts
+        - sudo docker run --env-file ./accounts/.env -p 3003:3003 -d fyipeproject/accounts:3.0.$CI_PIPELINE_IID
+        - sudo docker build -t fyipeproject/admin-dashboard:3.0.$CI_PIPELINE_IID ./admin-dashboard
+        - sudo docker run --env-file ./admin-dashboard/.env -p 3100:3100 -d fyipeproject/admin-dashboard:3.0.$CI_PIPELINE_IID
+        - sudo docker ps
+        - cd admin-dashboard
+        - npm ci
+        # try building, if there are warnings then this will fail
+        - npm run build
+        - npm run enterprise-test
+        - cd ..
+        - |
+            if [[ $CI_COMMIT_BRANCH != "master" ]] && [[ $CI_COMMIT_BRANCH != "release" ]]
+            then
+                chmod +x ./ci/scripts/storehash.sh
+                ./ci/scripts/storehash.sh build_n_test_enterprise_admin-dashboard admin-dashboard
+                ./ci/scripts/storehash.sh build_n_test_enterprise_admin-dashboard backend
+                ./ci/scripts/storehash.sh build_n_test_enterprise_admin-dashboard accounts
+                ./ci/scripts/storehash.sh build_n_test_enterprise_admin-dashboard licensing
+            fi
+    except:
+        refs:
+            - hotfix-master
+            - hotfix-release
